version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  test_local_invoke:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - sam/install
      - sam/local-start-api:
          template: "./sample_test/sam-app/template.yaml"
          endpoint: "hello"

workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          orb-name: circleci/aws-sam-serverless
          context: orb-publishing # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          requires:
            - orb-tools/lint
            - orb-tools/pack
      # Trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # Run any integration tests defined within the `jobs` key.
      - test_local_invoke:
          context: serverless-framework-orb-testing
      - sam/deploy:
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
          name: deploy-job-test-app
          template: "./sample_test/sam-app/template.yaml"
          stack-name: "orb-deploy-job-test-1"
          s3-bucket: "orb-testing"
          context: serverless-framework-orb-testing
          # python_version: "3.7.0" not used in container builds, adds significant time to job
      - sam/deploy:
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM
          name: deploy-job-test-container
          template: "./sample_test/sam-container/template.yaml"
          stack-name: "orb-deploy-job-test-2"
          image-repositories: $DEMO_IMG_URI
          context: serverless-framework-orb-testing
          validate: false
          # python_version: "3.7.0" not used in container builds, adds significant time to job
      # Publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/aws-sam-serverless
          bot-token-variable: GHI_TOKEN
          bot-user: cpe-bot
          context: orb-publishing
          add-pr-comment: false
          ssh-fingerprints: 12:0a:59:7e:51:fd:ed:24:8b:98:d3:f1:f4:b5:21:a4
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          requires:
            - test_local_invoke
          filters:
            branches:
              only: master
